---

- name: Dependencies are installed.
  apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
    state: present

- name: Add jenkins apt key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add jenkins repo
  apt_repository:
    repo: "deb http://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins
    update_cache: yes

- name: Install java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Install jenkins
  apt:
    name: jenkins
    state: present